version: "3.9"

services:
  dev:
    image: rumblekongleague/discord-bot
    env_file:
      - $PWD/.env
    ports:
      - "5050"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    restart: always
    command: --label-enable --cleanup --interval 900